config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :videos, only: [:index, :new, :create]
  root to: 'videos#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/video.rb
class Video < ApplicationRecord
  YT_LINK_FORMAT = /\A.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*/i

  validates :link, presence: true, format: YT_LINK_FORMAT
end

app/models/video_observer.rb
class VideoObserver < ActiveRecord::Observer
  def before_save(resource)
    video = Yt::Video.new url: resource.link
    resource.uid = video.id
    resource.title = video.title
    resource.likes = video.like_count
    resource.dislikes = video.dislike_count
    resource.published_at = video.published_at
  rescue Yt::Errors::NoItems
    resource.title = ''
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
    @videos = Video.order('created_at DESC')
  end

  def new
    @video = Video.new
  end

  def create
    @video = Video.new(video_params)
    if @video.save
      flash[:success] = 'Video added!'
      redirect_to root_url
    else
      render :new
    end
  end

  private

    def video_params
      params.require(:video).permit(:link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YtVideosV3</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://www.google.com/jsapi"></script>
    <script src="https://www.youtube.com/iframe_api"></script>
  </head>

  <body>
    <div class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <%= link_to 'YT APIv3', root_path, class: 'navbar-brand' %>
        </div>
        <ul class="nav navbar-nav">
          <li><%= link_to 'Videos', root_path %></li>
          <li><%= link_to 'Add Video', new_video_path %></li>
        </ul>
      </div>
    </div>

    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>">
          <%= value %>
        </div>
      <% end %>
    </div>

    <%= yield %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="panel panel-danger">
    <div class="panel-heading">
      <h3 class="panel-title">The following errors were found while submitting the form:</h3>
    </div>

    <div class="panel-body">
      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/videos/index.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Share your videos with the world!</h1>
    <p>Click the button below to share your video from YouTube.</p>
    <p>
      <%= link_to 'Add video now!', new_video_path, class: 'btn btn-primary btn-lg' %>
    </p>
  </div>
</div>

<% if @videos.any? %>
  <div class="container">
    <h1>Latest videos</h1>
    <div id="player-wrapper"></div>
  </div>

  <% @videos.in_groups_of(3) do |group| %>
    <div class="row">
      <% group.each do |video| %>
        <% if video %>
          <div class="col-md-4">
            <div class="yt_video thumbnail">
              <%= link_to image_tag("https://img.youtube.com/vi/#{video.uid}/mqdefault.jpg",
                alt: video.title, class: 'img-rounded'),
                "https://www.youtube.com/watch?v=#{video.uid}", target: '_blank' %>
              <div class="caption">
                <h5><%= video.title %></h5>
                <p>Published at <%= video.published_at.strftime('%-d %B %Y %H:%M:%S') %></p>
                <p>
                  <span class="glyphicon glyphicon glyphicon-thumbs-up"></span> <%= video.likes %>
                  <span class="glyphicon glyphicon glyphicon-thumbs-down"></span> <%= video.dislikes %>
                </p>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/videos/new.html.erb
<div class="container">
  <h1>New video</h1>

  <%= form_for @video do |f| %>
    <%= render 'shared/errors', object: @video %>

    <div class="form-group">
      <%= f.label :link %>
      <%= f.text_field :link, class: 'form-control', required: true %>
      <span class="help-block">A link to the video on YouTube.</span>
    </div>

    <%= f.submit class: 'btn btn-primary' %>
  <% end %>
</div>